-- 001_initial is materialised by `prom-migrate` from src/prom_service/db.py and recorded in
-- prom_schema_migrations. The migration boundary is restricted to prom_* tables in the
-- application's PostgreSQL database. Application startup never calls schema creation.
